In [2]:
import numpy as np


In [4]:
# Player runs data (11 players, 5 matches each)
runs = np.array([
    [45, 50, 30, 60, 25],
    [10, 15, 5, 20, 12],
    [80, 60, 75, 100, 90],
    [25, 30, 20, 35, 40],
    [0, 5, 10, 0, 2],
    [50, 55, 60, 65, 70],
    [35, 40, 45, 50, 55],
    [100, 110, 120, 115, 125],
    [10, 12, 15, 10, 8],
    [70, 80, 85, 90, 95],
    [40, 45, 50, 55, 60]
])

In [6]:
#Total runs scored by each player
total_runs = np.sum(runs, axis=1)

In [8]:
print("Total runs by each player:\n", total_runs)

Total runs by each player:
 [210  62 405 150  17 300 225 570  55 420 250]


In [10]:
#Highest score made by any player in a single match
highest_score = np.max(runs)

In [12]:
print("\nHighest individual score in a match:", highest_score)


Highest individual score in a match: 125


In [14]:
# Average runs scored per match by each player
average_runs = np.mean(runs, axis=1)


In [16]:
print("\nAverage runs per match by each player:\n", average_runs)


Average runs per match by each player:
 [ 42.   12.4  81.   30.    3.4  60.   45.  114.   11.   84.   50. ]


In [4]:
import numpy as np

# Sales data: products (rows) x days (columns)
sales_data = np.array([
    [150, 200, 250, 300, 400, 350, 500],  # Product 1
    [120, 180, 210, 240, 310, 280, 400],  # Product 2
    [100, 130, 190, 220, 300, 270, 350],  # Product 3
    [80,  90,  150, 180, 240, 220, 300],  # Product 4
    [50,  60,  80,  100, 130, 120, 180]   # Product 5
])

In [8]:
# 1. Shape of the array
shape = sales_data.shape
print("\nShape of sales_data:", shape)


Shape of sales_data: (5, 7)


In [10]:
# 2. Number of dimensions
dimensions = sales_data.ndim
print("Number of dimensions:", dimensions)

Number of dimensions: 2


In [12]:
# 3. Data type of elements
data_type = sales_data.dtype
print("Data type of elements:", data_type)

Data type of elements: int32


In [14]:
# 4. Total number of elements
total_elements = sales_data.size
print("Total number of elements:", total_elements)

Total number of elements: 35


In [16]:
# 5. Total memory used (in bytes)
memory_bytes = sales_data.nbytes
print("Total memory used (bytes):", memory_bytes)

Total memory used (bytes): 140


In [22]:
# 6. Retrieve specific sales data
product3_day4 = sales_data[2, 3]
product1_all = sales_data[0, :]
last_2_days = sales_data[:, -2:]
print("\nProduct 3 on Day 4:", product3_day4)
print("All sales for Product 1:", product1_all)
print("Sales data for the last 2 days:\n", last_2_days)


Product 3 on Day 4: 220
All sales for Product 1: [150 200 250 300 400 350 500]
Sales data for the last 2 days:
 [[350 500]
 [280 400]
 [270 350]
 [220 300]
 [120 180]]


In [24]:
# 7. Extract specific parts
first_3_products = sales_data[:3, :]
sales_last_2_days = sales_data[:, -2:]
print("\nSales data for the first 3 products:\n", first_3_products)
print("Sales data for the last 2 days:\n", sales_last_2_days)


Sales data for the first 3 products:
 [[150 200 250 300 400 350 500]
 [120 180 210 240 310 280 400]
 [100 130 190 220 300 270 350]]
Sales data for the last 2 days:
 [[350 500]
 [280 400]
 [270 350]
 [220 300]
 [120 180]]


In [26]:
# 8. Transpose the array
transposed_data = sales_data.T
print("\nTransposed sales data:\n", transposed_data)


Transposed sales data:
 [[150 120 100  80  50]
 [200 180 130  90  60]
 [250 210 190 150  80]
 [300 240 220 180 100]
 [400 310 300 240 130]
 [350 280 270 220 120]
 [500 400 350 300 180]]
